// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// boostrap_proximity_random
arma::vec boostrap_proximity_random(arma::mat errors0, arma::mat errors, arma::vec errors0Mean, arma::vec errorsMean, arma::mat Bindex, double epsilon, double epsilon2, double alpha, arma::mat sigmaLeft, int K, int selectionType, arma::vec sds);
RcppExport SEXP _nextdoor_boostrap_proximity_random(SEXP errors0SEXP, SEXP errorsSEXP, SEXP errors0MeanSEXP, SEXP errorsMeanSEXP, SEXP BindexSEXP, SEXP epsilonSEXP, SEXP epsilon2SEXP, SEXP alphaSEXP, SEXP sigmaLeftSEXP, SEXP KSEXP, SEXP selectionTypeSEXP, SEXP sdsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type errors0(errors0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type errors(errorsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type errors0Mean(errors0MeanSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type errorsMean(errorsMeanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Bindex(BindexSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon2(epsilon2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigmaLeft(sigmaLeftSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type selectionType(selectionTypeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sds(sdsSEXP);
    rcpp_result_gen = Rcpp::wrap(boostrap_proximity_random(errors0, errors, errors0Mean, errorsMean, Bindex, epsilon, epsilon2, alpha, sigmaLeft, K, selectionType, sds));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nextdoor_boostrap_proximity_random", (DL_FUNC) &_nextdoor_boostrap_proximity_random, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_nextdoor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
