# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

boostrap_proximity_random <- function(errors0, errors, errors0Mean, errorsMean, Bindex, epsilon, epsilon2, alpha, sigmaLeft, K, selectionType, sds) {
    .Call('_nextdoor_boostrap_proximity_random', PACKAGE = 'nextdoor', errors0, errors, errors0Mean, errorsMean, Bindex, epsilon, epsilon2, alpha, sigmaLeft, K, selectionType, sds)
}

